# Generated by Django 4.2.5 on 2023-09-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="state_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0100", "File pending"),
                    ("0201", "File downloaded"),
                    ("0202", "File unzipped"),
                    ("0203", "File unpickled"),
                    ("unkn", "Unknown"),
                    ("err", "Error"),
                ],
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="from_state_code",
            field=models.CharField(
                choices=[
                    ("0100", "File pending"),
                    ("0201", "File downloaded"),
                    ("0202", "File unzipped"),
                    ("0203", "File unpickled"),
                    ("unkn", "Unknown"),
                    ("err", "Error"),
                ],
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="metric",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="metric",
            name="to_state_code",
            field=models.CharField(
                blank=True,
                choices=[
                    ("0100", "File pending"),
                    ("0201", "File downloaded"),
                    ("0202", "File unzipped"),
                    ("0203", "File unpickled"),
                    ("unkn", "Unknown"),
                    ("err", "Error"),
                ],
                max_length=4,
                null=True,
            ),
        ),
    ]
