# Generated by Django 4.2.5 on 2023-09-25 09:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scheduling_app",
            "0003_remove_metric_file_size_file_file_size_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="deadline",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
