# Generated by Django 4.2.5 on 2023-09-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_app", "0004_file_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
