# Generated by Django 4.2.5 on 2023-10-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_app", "0005_alter_file_deadline"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pod",
            fields=[
                (
                    "pod_identifier",
                    models.UUIDField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=255)),
                ("namespace", models.CharField(max_length=255)),
                (
                    "ip",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("labels", models.JSONField(blank=True, null=True)),
                ("created_date", models.DateTimeField()),
                (
                    "last_status_update",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="metric",
            name="file",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="from_state_code",
        ),
        migrations.RemoveField(
            model_name="metric",
            name="to_state_code",
        ),
        migrations.AddField(
            model_name="file",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="scheduling_app.file",
            ),
        ),
        migrations.AddField(
            model_name="metric",
            name="source_file",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="metric",
                serialize=False,
                to="scheduling_app.file",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="file",
            name="process_step",
            field=models.CharField(
                choices=[
                    ("new", "new file"),
                    ("scheduled", "scheduled for processing"),
                    ("processing", "check the file state for the progress"),
                    ("finished", "finished processing"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="pod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="files",
                to="scheduling_app.pod",
            ),
        ),
    ]
