# Generated by Django 4.2.5 on 2023-10-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "scheduling_app",
            "0006_pod_remove_metric_file_remove_metric_from_state_code_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="expected_duration_at_schedule_time",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
