# Generated by Django 4.2.5 on 2023-10-18 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_app", "0007_metric_expected_duration_at_schedule_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("has_started", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TaskQueueSourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expected_duration", models.DurationField()),
                ("is_popped", models.BooleanField(default=False)),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="scheduling_app.file",
                    ),
                ),
                (
                    "task_queue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="scheduling_app.taskqueue",
                    ),
                ),
            ],
        ),
    ]
