# Generated by Django 4.2.5 on 2023-11-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_app", "0008_taskqueue_taskqueuesourcefile"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="total_kwh_used",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
