# Generated by Django 4.2.5 on 2023-11-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_app", "0009_metric_total_kwh_used"),
    ]

    operations = [
        migrations.AddField(
            model_name="metric",
            name="max_concurrency_at_execution_time",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
