# Generated by Django 4.2.5 on 2023-11-09 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_app", "0010_metric_max_concurrency_at_execution_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metric",
            name="total_kwh_used",
        ),
        migrations.AddField(
            model_name="metric",
            name="total_co2_emitted",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="MetricKwhMeasurement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_time", models.DateTimeField()),
                ("kwh", models.FloatField()),
                (
                    "metric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kwh_measurements",
                        to="scheduling_app.metric",
                    ),
                ),
            ],
        ),
    ]
