# Generated by Django 4.2.5 on 2023-11-11 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scheduling_app", "0011_remove_metric_total_kwh_used_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="metric",
            name="total_co2_emitted",
        ),
    ]
