---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: {{.Values.service.name}}
  name: {{.Values.service.name}}
spec:
  ports:
    - name: {{.Values.service.externalPort}}-tcp
      port: {{.Values.service.externalPort}}
      protocol: TCP
      targetPort: {{.Values.service.internalPort}}-tcp
  selector:
    name: {{.Values.deployment.name}}
  sessionAffinity: None
  type: ClusterIP
  internalTrafficPolicy: Cluster
