from django.contrib import admin
from django.db import models


class Pod(models.Model):
    pod_identifier = models.UUIDField(primary_key=True)
    """
    The pod_identifier is the UUID of the pod generated by the scheduler to assign
    files to it, it is NOT the docker container ID.
    """

    name = models.CharField(max_length=255)
    namespace = models.CharField(max_length=255)
    ip = models.CharField(max_length=255, null=True, blank=True)
    status = models.CharField(max_length=255, null=True, blank=True)
    labels = models.JSONField(null=True, blank=True)
    created_date = models.DateTimeField()
    last_status_update = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.name


class PodAdmin(admin.ModelAdmin):
    list_display = (
        "pod_identifier",
        "name",
        "namespace",
        "ip",
        "status",
        "created_date",
        "last_status_update",
    )

    search_fields = ("pod_identifier", "name", "namespace", "ip", "status")

    def has_add_permission(self, request):
        return True

    def has_change_permission(self, request, obj=None):
        return True
